apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-ingress
  namespace: library-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: library.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: library-nginx
            port:
              number: 80
  - host: api.library.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: library-app
            port:
              number: 8000
  - host: grafana.library.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: library-grafana
            port:
              number: 3000
  - host: prometheus.library.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: library-prometheus
            port:
              number: 9090