apiVersion: v1
kind: Secret
metadata:
  name: library-secrets
  namespace: library-system
type: Opaque
data:
  SECRET_KEY: eW91ci1zZWNyZXQta2V5
  JWT_SECRET_KEY: eW91ci1qd3Qtc2VjcmV0
  POSTGRES_PASSWORD: bGlicmFyeV9wYXNz
  REDIS_PASSWORD: cmVkaXNfcGFzcw==
  GRAFANA_ADMIN_PASSWORD: YWRtaW4xMjM=